### ISSUE TITLE
Error 100: (#100) Missing parameter(s): customer_file_source

### ISSUE THREAD

**Issue by sreeramcapillary** [facebookarchive/php-graph-sdk#1032]
Hi,

Can somebody help me what exactly this meant..? 

I have used same php sdk for several app to create custom audience.

But i am facing this error from past 2 days.

Thanks in advance.

**Comment by gamalan** [comment]
@sreeramcapillary Referring to its [marketing apidoc](https://developers.facebook.com/docs/marketing-api/reference/custom-audience#Creating), it seems it is a necessary parameter for the new version. You could just pick from the available value(USER_PROVIDED_ONLY, PARTNER_PROVIDED_ONLY, BOTH_USER_AND_PARTNER_PROVIDED)

**Comment by sreeramcapillary** [comment]
@gamalan. I figured it out couple of days back. Thanks for your help.!!

**Comment by BinRoq** [comment]
@gamalan. I figured it out couple of days back. Thanks for your help.!!
