### ISSUE TITLE
Facebook Graph API error response not connected to authentication/authorization resulted in FacebookAuthenticationException

### ISSUE THREAD

**Issue by JankesJanco** [facebookarchive/php-graph-sdk#1035]
From facebook graph API I get this error response (with http status code 400):
```json
"error": {
      "message": "No node specified",
      "type": "GraphMethodException",
      "code": 100,
      "fbtrace_id": "E0rEFfe+iGK"
}
```
This error was then translated to `FacebookAuthenticationException` which seems incorrect to me.

#### How I got this error response from Facebook Graph Api
I was calling this API endpoint
```
/{profileId}/posts
```
but I called it with `profileId = ""` (empty profileId). This is of course error, but probably it should not be translated to the `FacebookAuthenticationException`. Access token I used in this request was valid and not expired.

**Comment by yguedidi** [comment]
@JankesJanco thanks! You're probably right! I'd be happy to accept a PR that fix that! :)
