### ISSUE TITLE
Cannot declare class Facebook\GraphNodes\Collection

### ISSUE THREAD

**Issue by ZyberSE** [facebookarchive/php-graph-sdk#1040]
I'm having a really strange issue that occurs every now and then, usually it's a few weeks in-between and this is an api with a fair amount to hit's every sec.

FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot declare class Facebook\GraphNodes\Collection, because the name is already in use in /var/www/api.xxxxxxxx.com/v1/_classes/Facebook/GraphNodes/Collection.php on line 39

I'm running:
 - Facebook PHP SDK 5.6.2
 - NginX 1.10.3
 - PHP 7.0.30
 - Ubuntu 16.04.1 in AWS EC2

I can't find any other issues in the logs and as soon as I reboot the server it starts working again. Just restarting php or NginX won't help.

The server is only running this, no db or anything.
I have confirmed that no other .php file contains the word "Collection" other than those in ./Facebook.

Has anyone seen anything like this before and could point me in some direction? Currently I'm out of ideas..

**Comment by yguedidi** [comment]
@ZyberSE I think you're using the autoload.php file. Take a look at it ;)
I strongly suggest you to use composer for your vendors

**Comment by yguedidi** [comment]
@ZyberSE or you use both, the SDK one and composer
