### ISSUE TITLE
not getting user gender info with api v3.1.

### ISSUE THREAD

**Issue by codem360** [facebookarchive/php-graph-sdk#1042]
I am using graph api v3.1 with php sdk everything is fine but my code not returning user gender info.
I have permission in my app for gender. Only gender return for same user which create app, not getting gender of other user.

I am using this Code...
"/me?fields=id,first_name,last_name,email,gender"

**Comment by uxieme** [comment]
Hi, how did you solved issue? :)

**Comment by otymartin** [comment]
@ucze I think you must add "user_gender" under Facebook permissions parameter. Before I think you could fetch gender as part of "public_profile" permission.
