### ISSUE TITLE
Cannot post to fanpage with Facebook App

### ISSUE THREAD

**Issue by flameblue59** [facebookarchive/php-graph-sdk#1047]
Hi, I am building a system to share a post automatically from [hewandijual.com](https://hewandijual.com) to our official fanpage but when I run it. I get this following problem. I am trying to run it since yesterday but this error is never lifted.

`Fatal error: Uncaught Facebook\Exceptions\FacebookAuthenticationException: You have been temporarily blocked from performing this action. in /home/admin/hewandijual/vendor/facebook/graph-sdk/src/Facebook/Exceptions/FacebookResponseException.php:133 Stack trace: #0 /home/admin/hewandijual/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse)) #1 /home/admin/hewandijual/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException() #2 /home/admin/hewandijual/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody() #3 /home/admin/hewandijual/vendor/facebook/graph-sdk/src/Facebook/FacebookClient.php(224): Facebook\FacebookResponse->__construct(Object(Facebook\FacebookRequest), '{"error":{"mess...', 400, Array) #4 /home/admin/hewandijual/vendor/facebook/graph-sdk/src/Facebook/Facebook.php(469): Facebook\FacebookClient->sendRequest(Objec in /home/admin/hewandijual/vendor/facebook/graph-sdk/src/Facebook/Exceptions/FacebookResponseException.php on line 133`

**Comment by mathfrick** [comment]
Yeah, i have that error too... ma script working fine and after a couple of hour i get that:

#0 /home/maplatef/public_html/Dev/Bingo/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse)) #1 /home/maplatef/public_html/Dev/Bingo/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException() #2 /home/maplatef/public_html/Dev/Bingo/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody() #3 /home/maplatef/public_html/Dev/Bingo/vendor/facebook/graph-sdk/src/Facebook/FacebookClient.php(224): Facebook\FacebookResponse->__construct(Object(Facebook\FacebookRequest), '{"error":{"mess...', 400, Array) #4 /home/maplatef/public_html/Dev/Bingo/vendor/facebook/graph-sdk/src/Facebook/Authentication/OAuth2Client.php(277): Facebook\FacebookClient->sendRequest(Object(Facebook\FacebookRequest)) #5 /home/maplatef/public_html/Dev/Bingo/vendor/facebook/graph-sdk/src/Facebook/Authentication/OAuth2Client.php(226): Facebook\Authentication\OAuth2Client->sendRequestWithClientParams('/oauth/access_t...', Array) #6 /home/maplatef/public_html/Dev/Bingo/vendor/facebook/graph-sdk/src/Facebook/Authentication/OAuth2Client.php(166): Facebook\Authentication\OAuth2Client->requestAnAccessToken(Array) #7 /home/maplatef/public_html/Dev/Bingo/vendor/facebook/graph-sdk/src/Facebook/Helpers/FacebookRedirectLoginHelper.php(228): Facebook\Authentication\OAuth2Client->getAccessTokenFromCode('AQDdBEhvN_QD2pv...', 'https://www.ma-...') #8 /home/maplatef/public_html/Dev/Bingo/config.php(56): Facebook\Helpers\FacebookRedirectLoginHelper->getAccessToken() #9 /home/maplatef/public_html/Dev/Bingo/INC/includes.php(3): require('/home/maplatef/...') #10 /home/maplatef/public_html/Dev/Bingo/index.php(1): require_once('/home/maplatef/...') #11 {main}

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
