### ISSUE TITLE
$helper->getAccessToken() return an URL

### ISSUE THREAD

**Issue by shengfa** [facebookarchive/php-graph-sdk#1048]
function throughFacebookCallback($request, $response, $args) {
&nbsp;&nbsp;&nbsp;&nbsp;$helper = $this->facebook->getRedirectLoginHelper();
&nbsp;&nbsp;&nbsp;&nbsp;try {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$accessToken = $helper->getAccessToken();
&nbsp;&nbsp;&nbsp;&nbsp;} catch( \Facebook\Exceptions\FacebookResponseException $e ) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// When Graph returns an error
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;echo 'Graph returned an error: ' . $e->getMessage();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;exit;
&nbsp;&nbsp;&nbsp;&nbsp;} catch( \Facebook\Exceptions\FacebookSDKException $e ) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// When validation fails or other local issues
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;echo 'Facebook SDK returned an error: ' . $e->getMessage();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;exit;
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;echo $accessToken;
}

The result $accessToken in the end is a link, not access_token

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.
