### ISSUE TITLE
How can we receive user_token without redirect for login

### ISSUE THREAD

**Issue by VirendraArekar** [facebookarchive/php-graph-sdk#1052]
Anyone guide me i try to **create user_token without redirect** but not getting a success so how can i do this.Also one question  **how can i post on some other user wall from my side with using php.**

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.
