### ISSUE TITLE
php Facebook Login issue

### ISSUE THREAD

**Issue by ketanvekariya** [facebookarchive/php-graph-sdk#1053]
php login is working fine but some reason its stopped working. The code will be display on the same page 
for ex. www.mysite.com/?code =dsadasdacxxcx325dfsr435 ...
so when i debug its gives me error like "facebook cross-site request forgery validation failed "state"

I just echo url on Oauth2Client.php =>  getAuthorizationUrl() =>copy url and paste in browser.

Its working fine.

But i dont understand the exact issue.

Please anyone can let me know what will be the issue?

**Comment by gianpaolodn** [comment]
Possible duplicate of #1049

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK! @ketanvekariya it looks like a session issue, make sure the session is started.

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.
