### ISSUE TITLE
Getting error on Facebook\\GraphNodes\\Collection

### ISSUE THREAD

**Issue by DutchEcho** [facebookarchive/php-graph-sdk#1058]
Good day to you all,

I'm trying to get some info from my own Facebook account about the events I have selected to be interested in. But it is giving an error and i really don't know why I get an error. I have below code:

````
<?php
    require_once  '../data/Facebook/autoload.php';
    $fb = new \Facebook\Facebook([
        'app_id' => '{app id}',
        'app_secret' => '{app secret}',
        'default_graph_version' => 'v3.1',
        'default_access_token' => '{access token}', // optional
    ]);

    try {
        // Returns a `FacebookFacebookResponse` object
        $response = $fb->get(
            '/me?fields=events.limit(1)'
        );
    } catch(FacebookExceptionsFacebookResponseException $e) {
        echo 'Graph returned an error: ' . $e->getMessage();
        exit;
    } catch(FacebookExceptionsFacebookSDKException $e) {
        echo 'Facebook SDK returned an error: ' . $e->getMessage();
        exit;
    }
    $graphNode = $response->getGraphNode();
    //print_r( $graphNode);
 ?>
````
I get below error response:

`FastCGI: server "/var/run/php72-cgi/php-cgi" stderr: PHP message: PHP Fatal error: Class 'Facebook\\GraphNodes\\Collection' not found in /www/test/dashboard/data/Facebook/GraphNodes/GraphNode.php on line 31`
I'm off course using all the original docs. But for some reason it is not working. When I comment out line `$graphNode = $response->getGraphNode();` then there is no problem. And i do get an expected response when I `print_r` the `$response`

I hope someone out here know how to resolve it.

**Comment by yguedidi** [comment]
Looks like an autoloading issue. I see you're using the autoload file.
I strongly suggest you to use composer for autoloding.
