### ISSUE TITLE
URL blocked: This redirect failed because the redirect URI is not white-listed in the app's client OAuth settings.

### ISSUE THREAD

**Issue by codearthungary** [facebookarchive/php-graph-sdk#1059]
Hi guys,
I get this message from FB: "URL blocked: This redirect failed because the redirect URI is not white-listed in the app's client OAuth settings. Make sure that the client and web OAuth logins are on and add all your app domains as valid OAuth redirect URIs."

It worked so far and had no problem with it. I already downloaded and installed the latest PHP-SDK, but not changed. I check all my URI, and server in white list and all OK. I wrote the FB support, they say this: "I checked your URL and it seems correct to me. I see that you are using the PHP SDK. There was a bug on that SDK which was stopping people for login with Facebook. Make sure you are using the last version of the SDK".

Any solution or suggestion?

**Comment by MonggulTeam** [comment]
i had this problem. 
which  is correct url for Valid OAuth Redirect URIs. 
is this correct ? (https://www.example.com/my-fb-login/fb-callback.php)

Any solution or suggestion?

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK! The bug was fix in 5.6.2, make sure you use this version or higher.

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.

**Comment by codearthungary** [comment]
Hi yguedidi, I'm using 5.6.3 sdk but the error is permanent. Server IP added to the white list. My callback URI: "https://www.facebook.com/v2.12/dialog/oauth?client_id=1640455976014380&amp;state=3182eba045b4f7bdfd9dc9fa395a0f7e&amp;response_type=code&amp;sdk=php-sdk-5.6.3&amp;redirect_uri=https%3A%2F%2Ffishinfobay.com%2Fauth%2Ffacebooklogin&amp;scope="
I'm has got check my all redirect URIs by URI validation checker on the FB and that say all OK.
