### ISSUE TITLE
Call to undefined function Facebook\\Facebook::api()

### ISSUE THREAD

**Issue by sureshsuthar555** [facebookarchive/php-graph-sdk#1062]
Hello 
I am trying to get list of all friends but when calling following script 

require_once 'src/Facebook/autoload.php'; 

$fb = new Facebook\Facebook([
  'app_id' => 'xxxxxxxxxxxxxxxxx',
  'app_secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'default_graph_version' => 'v2.12',
]);

$friends = $fb->api('/me/friends');

it throw error "PHP Fatal error:  Uncaught Error: Call to undefined method Facebook\\Facebook::api()"

Can you please help to me to find out root cause of this error.

Also i want to publish a post on all friend wall.
Which API Api will help me to do my job?

**Comment by orynider** [comment]
Try
``		require_once("src/Facebook/autoload.php");

		$app_id = 'xxxxxxxxxxxxxxxxx';
		$app_secret = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';

		$facebook_config = array('appId'  => $app_id, 'secret' => $app_secret, 'default_graph_version' => 'v2.12');
		$fb = new Facebook\Facebook($facebook_config);

**Comment by orynider** [comment]
`		require_once("src/Facebook/autoload.php");
		$app_id = 'xxxxxxxxxxxxxxxxx';
		$app_secret = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';

		$facebook_config = array('appId'  => $app_id, 'secret' => $app_secret, 'default_graph_version' => 'v2.12');
		$fb = new Facebook\Facebook($facebook_config);`

**Comment by yguedidi** [comment]
it looks like you wrot v4 code, please follow the v5 doc.
