### ISSUE TITLE
Hasta hace 2 días estaba funcionando normal el login con Facebook bajo PHP, pero ahora dejó de funcionar y con ninguna cuenta se puede loguear.

### ISSUE THREAD

**Issue by kaaf030191** [facebookarchive/php-graph-sdk#1080]
Buen día; sólo para informar lo siguiente.

Hasta hace 2 días estaba funcionando normal el login con Facebook bajo PHP, pero ahora dejó de funcionar y con ninguna cuenta se puede loguear. El único error que sale es *Offset 1* al momento de llamar a la función *getAccessToken*.

Tal vez puedan revisarlo.

Saludos.

**Comment by pako-pl** [comment]
Please see https://github.com/facebook/php-graph-sdk/issues/1076

**Comment by kaaf030191** [comment]
> Please see #1076

Thank you, this solution it's correct.
