### ISSUE TITLE
Facebook php-graph-sdk v5

### ISSUE THREAD

**Issue by sushantlp** [facebookarchive/php-graph-sdk#1086]
I use the following code to get facebook pages data.

`$fb->get('/'.$pageId.'/posts?fields=attachments,likes,comments,message,created_time',$accessToken);`

This code worked just fine until now, but from couple of days it has started giving an exception saying

> Undefined Offset 1

I am currently using facebook sdk v5.6, facebook graph v3.2, PHP v7.0.

**Comment by fbourigault** [comment]
Have you tried sdk 5.7? Your error is probably the one fixed in #1079.

**Comment by sushantlp** [comment]
Thanks its working
