### ISSUE TITLE
The sdk not working at all - can not parse http/2 response code

### ISSUE THREAD

**Issue by hanakivan** [facebookarchive/php-graph-sdk#1091]
The faulty method is this: 

`public function setHttpResponseCodeFromHeader($rawResponseHeader)
    {
        preg_match('|HTTP/\d\.\d\s+(\d+)\s+.*|', $rawResponseHeader, $match);
        $this->httpResponseCode = (int)$match[1];
    }`

it will parse only HTTP/1.1, will not parse HTTP/2 - this makes current version of sdk useless

The faulty version is 5.6.3 that is available on packagist.

**Comment by ilkin007** [comment]
Having the same issue...

**Comment by ilkin007** [comment]
In case we change the code to:
```
public function setHttpResponseCodeFromHeader($rawResponseHeader)
{
    preg_match('|HTTP/\d\s+(\d+)|', $rawResponseHeader, $match);
    $this->httpResponseCode = (int)$match[1];
}
```

It works again :) Just changed regular expression to accept HTTP/2 .
But it would be cool if we add it for both versions of HTTP (1.1 and 2)

**Comment by fbourigault** [comment]
I have the same issue. I moved to the `stream` `http_client_handler` so it doesn't use `h2` to perform requests.

**Comment by jakubkulhan** [comment]
Ouch, just experienced this bug in our app. Any time frame when it will be fixed?

**Comment by finwe** [comment]
PR fixing this was merged almost a month ago. https://github.com/facebook/php-graph-sdk/pull/1079

**Comment by julienbourdeau** [comment]
I'm hoping we can get a patch version rather than wait for 5.7. 🙏

**Comment by ruudk** [comment]
@yguedidi Having the same issue, why isn't this patched in 5.6?

**Comment by ruudk** [comment]
Also, there is no way of using `5.x` in Composer because it's not registered as a branch alias (see https://packagist.org/packages/facebook/graph-sdk)

**Comment by julienbourdeau** [comment]
Honestly, I'm not sure a release is coming soon, probably not at this time of the year. 
I forked the repo and used my own branch for now, I'll get rid of this when 5.7 is out.

1. fork repository
2. update `composer.json`
```json
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/julienbourdeau/php-graph-sdk"
        }
    ],
    "require": {
        "php": "^7.1.3",
        "facebook/graph-sdk": "5.x-dev"
    },
```
3. delete vendor folder (just in case) `rm -rf vendor/facebook`
4. Update with `composer update`

**Comment by ruudk** [comment]
@julienbourdeau FYI, No need for a fork, you can also do this:
```json
"repositories": [{
            "type": "vcs",
            "url": "http://github.com/facebook/php-graph-sdk"
        }
],
    "require": {
        "php": "^7.1.3",
        "facebook/graph-sdk": "5.x-dev"
    },
```

**Comment by julienbourdeau** [comment]
That's what I expected but for some reason, it didn't work. I didn't want waste too much time so I didn't look into the details ¯\_(ツ)_/¯

**Comment by yguedidi** [comment]
5.7.0 finally released! Sorry for the delay.. Thanks to who provide workarounds!
