### ISSUE TITLE
Can't Post Note to Pages

### ISSUE THREAD

**Issue by setdjod** [facebookarchive/php-graph-sdk#1114]
**My code:**
```php
$fb->post("MY_PAGE_ID/notes", [ 
	"subject" => "Subject Notes",
	"message" => "Messages Notes"
], $token_pages);
```
Then result:
An uncaught Exception was encountered
Message: (#200) This endpoint is deprecated since the required permission **publish_actions is deprecated**
Filename: vendor/facebook/graph-sdk/src/Facebook/Exceptions/FacebookResponseException.php

How to resolve? or what is best practice for my problem?
Thanks

**Comment by lukadriel7** [comment]
Hello @setdjod , Where you able to solve your issue ? If yes how did you do it ?
