### ISSUE TITLE
How to upload multiple photos in a single facebook post 

### ISSUE THREAD

**Issue by Chamberlainfrancis** [facebookarchive/php-graph-sdk#1155]
I am trying to upload multiple photos in a single facebook post from my website using the PHP sdk version 4.0, I don't know if i can get any help from here on how to do it as I only know how to upload a single photo post, I have searched the entire Google for answers yet nothing, thanks in advance for the help.

**Comment by fd6130** [comment]
I just know page photos, but i believe the concept is almost the same.

You can upload as single unpublished photo, get their return id and make a post request to /feed

doc: https://developers.facebook.com/docs/graph-api/reference/page/photos/#multi

**Comment by kada-zaouak** [comment]
hello

**Comment by hassan22k** [comment]
Hii
