### ISSUE TITLE
FacebookResponseException : 无法加载网址: 这个 URL 的域名未包含应用的域名。为了能够加载 URL，请在应用设置的应用域名字段添加应用的所有域和子域

### ISSUE THREAD

**Issue by chenxinlong** [facebookarchive/php-graph-sdk#1158]
facebook graph SDK  throw a `FacebookResponseException` while call `$helper->getAccessToken()`。  Exception msg as below : 

```
FacebookResponseException : 无法加载网址: 这个 URL 的域名未包含应用的域名。为了能够加载 URL，请在应用设置的应用域名字段添加应用的所有域和子域
```

According to the exception message, this may be a setting problem. But this exception doesn't happen every time.

* SDK version : 5.7.0  

This issue may related to #983 . But I still couldn't find a solution to solve it both on [Facebook issue tracker](https://developers.facebook.com/bugs/) or stackoverflow。

**Comment by aszx0413** [comment]
同样遇到这个问题，请问解决了吗

**Comment by chenxinlong** [comment]
暂时没有解决。貌似翻qiang去访问 facebook 才会遇到这个问题，海外用户则不会遇到这个问题。

**Comment by Shimingli** [comment]
我也遇到了 https://m.facebook.com/v3.1/dialog/oauth?client_id=2883855415159978&state=rau9nu0va44c0aqlndaqvcim9u&redirect_uri=https%3A%2F%2Fwww.facebook.com%2Fconnect%2Flogin_success.html&scope=email&response_type=token&auth_type=rerequest&ret=login&fbapp_pres=0&logger_id=fc72b707-cd7a-4fd0-b17d-fb73c60c6e80&tp=unspecified&_rdr
