### ISSUE TITLE
Composer is not fetching the Facebook class

### ISSUE THREAD

**Issue by norey** [facebookarchive/php-graph-sdk#117]
I have
{
    "require": { 
        "facebook/php-sdk-v4": "dev-master"
    }
}

After I run php composer.phar install
I get
- vendor/
  - facebook/
  - composer/
  - autoload.php

The issue is, I don't see any definition of the Facebook class in autoload_classmap.php
I get an error when I try to use the Facebook object/class after requiring autoload.php
Did I do something wrong with composer?

**Comment by angelxmoreno** [comment]
I am having the same issue. I can use other classes but not class FacebookSession. It looks like Composer's autoloader is working but there is no FacebookSession class in the vendor/facebook/src/ dir.

```php
use Facebook\FacebookApp;
use Facebook\FacebookSession;

new FacebookApp('YOUR_APP_ID', 'YOUR_APP_SECRET'); //throws no errors
new FacebookSession('YOUR_APP_ID', 'YOUR_APP_SECRET'); // Fatal error: Class 'Facebook\FacebookSession' not found

**Comment by angelxmoreno** [comment]
I was pointing to the wrong build! I changed my composer entry from
`"facebook/php-sdk-v4": "dev-master"`
 to 
`"facebook/php-sdk-v4" : "4.0.*",`

... and now I am winning.

**Comment by zairwolf** [comment]
I tried `"facebook/php-sdk-v4" : "4.0.*",`. When I use `use Facebook\FacebookSession;`, it shows `Parse error: syntax error, unexpected 'use' (T_USE)`

**Comment by SammyK** [comment]
Hey @zairwolf - the Facebook PHP SDK requires PHP 5.4 or greater.

**Comment by zairwolf** [comment]
Hi @SammyK , my PHP is v5.5:)

**Comment by SammyK** [comment]
Your `use` statements also need to be at the very top of your script above all other code.

**Comment by zairwolf** [comment]
Absolutely. I added them just after vendor loaded. In fact I tried `Facebook\FacebookSession::setDefaultApplication`, it shows `Fatal error: Class 'FacebookSession' not found`. I guess even loaded `vendor/autoload.php`, it still needs to load some facebook php files manually?

**Comment by zairwolf** [comment]
WOW, fixed. Thanks @SammyK . I know the reason now.
If I don't use those namespaces, I have to add `Facebook\` before every class.
`$session = new Facebook\FacebookSession($token);
  $me = (new Facebook\FacebookRequest(
    $session, 'GET', '/me'
  ))->execute()->getGraphObject(Facebook\GraphUser::className());`
Then it works.
Otherwise, If I use namespaces, as you said, I must add them before any other initial codes.
