### ISSUE TITLE
Is this project maintained ??

### ISSUE THREAD

**Issue by williamdes** [facebookarchive/php-graph-sdk#1184]
`Latest commit 2d82506 on 11 Dec 2018` made me have a lot of doubts

Hosted in @facebookarchive make me have even more doubts.

The changelog pointing to a release in 2018 made it even worse: https://github.com/facebookarchive/php-graph-sdk/blob/5.x/CHANGELOG.md#5x

:man_shrugging: 

Last project update was in 2017 !!
https://github.com/facebookarchive/php-graph-sdk/projects/1

cc @JoelMarcey @viv001 please clear this situation :)

Ref: #1152

**Comment by redfluz** [comment]
Seem i can close fb login for my apps.. Security Reason..

**Comment by BenMorel** [comment]
**+1 Please clarify this situation.**

This repository is linked to from the [official docs](https://developers.facebook.com/docs/reference/php/), so we can reasonably expect that it's being maintained.

That being said, the last commit being in 2018 worries me a lot, too.

Plus, **I keep getting email alerts saying that my apps use the Graph API v2.x**, and it looks like this is because I'm using **the PHP SDK which is locked to an older version**:

https://github.com/facebookarchive/php-graph-sdk/blob/5.x/src/Facebook/Facebook.php#L61

@yguedidi @SammyK Could you please comment on this?

**Comment by bizmate** [comment]
@BenMorel  you can wait for others to reply about it if is maintained or not but you can change the API version and use a newer one if you wanted too. Especially now that v2.12 will be deprecated

**Comment by williamdes** [comment]
@bizmate I could not use a version superior to `v4.0` for fetching graph users..

**Comment by BenMorel** [comment]
@bizmate I'd obviously prefer to use a maintained version, rather than modifying the package. @williamdes thank you for mentioning that it works up to `v4.0`, though.

**Comment by a7madgamal** [comment]
I guess the answer is no -.-

**Comment by bizmate** [comment]
@BenMorel  you do not need to modify anything in the package. The README shows how to specify a different version. 
https://github.com/facebookarchive/php-graph-sdk/blame/5.x/README.md#L36
The default version is just if you do not specify an explicit version in your calls.

@williamdes I am testing with v6.0 and I do not see any problems but I do interact only with pages mainly so I am not sure if any other endpoint breaks.
Have you tried opening a bug in the facebook developers page? https://developers.facebook.com/support/bugs/ I know it is not nice to post there but if you cannot use api v6/5 someone from Facebook should pick this up and contribute to the project.

**Comment by BenMorel** [comment]
@bizmate Thank you for pointing this out! I had obviously missed this.

I'd still love to get an answer from Facebook though, it's scary to use a software that's broken by default (outdated Graph API version), and shows no sign of activity whatsoever.

**Comment by gfosco** [comment]
This project has been community maintained since version 4, but I see there's been a long gap... I will reach out to Yassine, but we may need to add additional committers.  If you would like to help out, please reach out to me at fjm@fb.com

**Comment by a7madgamal** [comment]
tbh it doesn't make much sense for an official sdk to be community maintained in the first place then deprecated without a clear reason or something to be replaced with 😅

**Comment by gfosco** [comment]
The goal (at least my personal goal) has always been to avoid deprecating and archiving it.  Back then (2014-2015) the community really got involved driving the switch from v3 to v4, and it was nice for it to just continue in place with Sammy/Yassine running it.  A fork elsewhere would be disruptive to the community, but of course is still an option. Facebook has also transferred ownership of repos to other orgs and community groups in the past (i.e. Parse, webdriver-php both are projects I was involved in).

**Comment by BenMorel** [comment]
Thanks for your reply, @gfosco. It's a bit sad to not have an SDK developed by Facebook themselves, though. It looks like relying on community support brought the project to a halt. And not having Facebook involved means that the SDK will always be (far) behind the API.

**Comment by olegatro** [comment]
facebook doesn`t have money to contribute to the php sdk really ?

shame

**Comment by PlusA2M** [comment]
What's the next best alternative for the system that based on PHP? 
I believe there are lots of web systems powered by WordPress, WooCommerce, etc. all using PHP.

**Comment by palicko** [comment]
It works with **v7.0** as well,
but I'm using it only to get access token via Facebook Login.

**Comment by fsmeier** [comment]
@gfosco @SammyK @yguedidi 
About the "community driven" point:
I see there are some more PRs and a lot of open issues. How can we support to make this repo up2date again? Do we need to find new community managers?

If we know what is needed/expected/wanted we can also bring this topic up in the next fb developers circles

If you want we can also have a small call to talk about possibilities. I would love to see this issue moving forward!

**Comment by Acen** [comment]
Suggest switching to: 
https://github.com/facebook/facebook-php-business-sdk

We migrated from this around 6 months ago.
Functionally, the two SDK match pretty well. 
Though the name spacing is super weird due to the ads referencing when entirely unrelated, but what can ya do.

**Comment by williamdes** [comment]
Hi!
Any Facebook people here to finally decide about this?

**Comment by williamdes** [comment]
🏓 NO BODY FUCKING CARES, THANKS FACEBOOK

It's archived but not archived. Anyway, closing this
