### ISSUE TITLE
FacebookRedirectLoginHelper::getLogoutUrl() does not work

### ISSUE THREAD

**Issue by deadmantfa** [facebookarchive/php-graph-sdk#126]
The current function creates a link but does not logout the user and does not redirect, it just opens the facebook page.
Below is the url created by the function
<a href="https://www.facebook.com/logout.php?next=https%3A%2F%2Fwww.epaisa.com&amp;access_token=XXXXX">Logout</a>

**Comment by rvarbanov** [comment]
@gfosco, do you know if this issue was fixed?

**Comment by SammyK** [comment]
Works for me
