### ISSUE TITLE
Parse signed request

### ISSUE THREAD

**Issue by ilves** [facebookarchive/php-graph-sdk#14]
Currently parseSignedRequest is private and throws error when oauth_token or code element is missing but for example when using page tab app then one should be able to parse the signed request as there are some important data for example if the user has liked the page, page_id etc. and when the user is not authed yet then there is no oauth_token or code element.

I suggest that parseSignedRequest should be public method and the oauth_token and code exception should be placed somewhere else for example inside newSessionFromSignedRequest method.

**Comment by sugumarv** [comment]
Fatal error: Uncaught exception 'Facebook\Exceptions\FacebookSDKException' with message 'Signed request has an invalid signature

**Comment by kloneets** [comment]
maybe you are using access token from wrong application?
