### ISSUE TITLE
AppSecret Proof implemention

### ISSUE THREAD

**Issue by willrowe** [facebookarchive/php-graph-sdk#26]
Do API requests include the 'appsecret_proof' parameter so that it will work when the corresponding option is enabled on an app?

**Comment by vnikolay** [comment]
Hello! When i posting to the user page wall or group it's ok, but if i post to the fan page its always show:
100 : Invalid appsecret_proof provided in the API argument. 
the code is
$params['appsecret_proof'] = hash_hmac('sha256', $session->getToken(), $app['secret']); 
$data = (new Facebook\FacebookRequest($session, $method ,$api_url,$params))->execute()->getGraphObject()->asArray();

Also i tryed to paste acces_token (not $session->getToken()) and other variations, but always get that error. In graph API explorer works fine.

Could you tell me in what i doing wrong? Thanks for help.

**Comment by SammyK** [comment]
@vnikolay The app secrete proof is generated for you automatically by the SDK so you don't need to send it in as a param.

**Comment by vnikolay** [comment]
Ok, but i get  error 100 : Invalid appsecret_proof provided in the API argument when i post to the fan page, when post to my own page or to group - no error, i dont now, how to solve this.

**Comment by SammyK** [comment]
Sounds like your using the wrong app secret.

**Comment by vnikolay** [comment]
Sorry, finally I found my bug. It was in access token for fan page, it did not live long and varies. Thanks.
