### ISSUE TITLE
OAuthException: Missing redirect_uri parameter (Error 191)

### ISSUE THREAD

**Issue by shaphiro** [facebookarchive/php-graph-sdk#274]
Hi I'm testing an application with SDK version 4.0.12. My Web Site Url on facebook is set to 'https://www.mydomain.com/app. Canvas url is also set to the same value (if this can be a problem)

This is my code in index.php: 

$helper = new FacebookRedirectLoginHelper('https://www.mydomain.com/app');
    try {
        $session = $helper->getSessionFromRedirect(); //ERROR HERE
    } catch(Exception $e) {
        print_r($e);
    }
    if ($session) {
      $accessToken = $session->getAccessToken();
      $longLivedAccessToken = $accessToken->extend();
    } else {
      echo "<script type='text/javascript'>top.location.href = \"{$helper->getLoginUrl()}\";</script>";
      exit();
    }

After the redirect I receive this error when is called $session = $helper->getSessionFromRedirect()

```
[statusCode:Facebook\FacebookRequestException:private] => 400
[rawResponse:Facebook\FacebookRequestException:private] => {"error":{"message":"Missing redirect_uri parameter.","type":"OAuthException","code":191}}
[responseData:Facebook\FacebookRequestException:private] => Array
    (
        [error] => Array
            (
                [message] => Missing redirect_uri parameter.
                [type] => OAuthException
                [code] => 191
            )
    )
```

...

The redirect_uri seems set correctly and I don't know why this error is returned.
Some help?
Thanks in advance.

**Comment by adithyamahesh596** [comment]
Can any one provide the solution in JavaScript?

**Comment by yguedidi** [comment]
@adithyamahesh596 you should ask StacjOverflow ;)
