### ISSUE TITLE
A little problem with FacebookJavaScriptLoginHelper

### ISSUE THREAD

**Issue by kerike** [facebookarchive/php-graph-sdk#278]
Hi guys,

I made the transition to sdk v4, and all things work pretty well. But i still get sometimes:

This authorization code has been used.
This authorization code has expired.

I am using FacebookJavaScriptLoginHelper, after an ajax call from the js facebook sdk. Should I convert the access token to long lived access token every time? What would be the solution to solve these problems. On the facebook docs I found something like this:

It's important to note that on first access, or if a session has since expired, these methods will operate on data that is one request-cycle stale. You will likely want to make an Ajax request when the login state changes in the Facebook SDK for JavaScript.

Any thoughts? Thank you very much.

**Comment by saikiranmarripati** [comment]
Hello @SammyK 

What you meant by " You can make sure that the JavaScript SDK is updating the cookie by calling FB.getLoginStatus()"

I am getting following error:

Facebook exception code :100
FacebookRequestException: This authorization code has been used.

      FB.init({
        appId: '{app_id}'',
        version: 'v2.6',
        channelUrl : '', 
        status     : true, 
        cookie     : true, 
        xfbml      : true  
      });
