### ISSUE TITLE
validateCsrf produces Error

### ISSUE THREAD

**Issue by mariusglauer** [facebookarchive/php-graph-sdk#292]
I'm using the latest dev version from the master branch.

My code only works when I uncomment this line:
https://github.com/facebook/facebook-php-sdk-v4/blob/master/src/Facebook/Helpers/FacebookRedirectLoginHelper.php#L171

Otherwise, I'm getting an FacebookSDKException with message 'Cross-site request forgery validation failed. Required param "state" missing.' in /vendor/facebook/php-sdk-v4/src/Facebook/Helpers/FacebookRedirectLoginHelper.php:194

That's my code:

```
$fb = new Facebook([
    'app_id' => Config::get('facebook.app_id'),
    'app_secret' => Config::get('facebook.app_secret'),
    'persistent_data_handler'   =>  new FacebookLaravelPersistentDataHandler()
]);

if (isset(Auth::user()->facebook_token) && !empty(Auth::user()->facebook_token))
{
    $accessToken = Auth::user()->facebook_token;
}
else
{
    $accessToken = $fb->getRedirectLoginHelper()->getAccessToken($fb->getClient(), url('publisher/autoposter'));
}
```

FacebookLaravelPersistentDataHandler.php:

```
class FacebookLaravelPersistentDataHandler implements \Facebook\PersistentData\PersistentDataInterface
{

public function get($key)
{
  return \Session::get('facebook.' . $key);
}

public function set($key, $value)
{
  \Session::put('facebook.' . $key, $value);
}

}
```

**Comment by xadim** [comment]
@SammyK Thanks for the support!
I'm having the same problem in Laravel 5. 
Dumping these 2 blocs : 
var_dump(\Session::get('facebook.state'));
var_dump(\Input::get('state'));
exit;
Return: NULL string(32) "c33aca7a0a0b99d4fa66b094cfcd3fe1"
This is my code:
// Generate a login URL
Route::get('/facebook/login', function(SammyK\LaravelFacebookSdk\LaravelFacebookSdk $fb) {
    $login_link = $fb
            ->getRedirectLoginHelper()
            ->getLoginUrl('http://my-local-domain.dev/facebook/callback', ['email', 'user_events']);

    echo '<a href="' . $login_link . '">Log in with Facebook</a>';
});


// Endpoint that is redirected to after an authentication attempt
Route::get('/facebook/callback', function(SammyK\LaravelFacebookSdk\LaravelFacebookSdk $fb)
{
    // Obtain an access token.
    try {
        $token = $fb->getAccessTokenFromRedirect();
    } catch (Facebook\Exceptions\FacebookSDKException $e) {
        dd($e->getMessage());
    }

    // Access token will be null if the user denied the request
    // or if someone just hit this URL outside of the OAuth flow.
    if (! $token) {
        // Get the redirect helper
        $helper = $fb->getRedirectLoginHelper();

        if (! $helper->getError()) {
            abort(403, 'Unauthorized action.');
        }

        // User denied the request
        dd(
            $helper->getError(),
            $helper->getErrorCode(),
            $helper->getErrorReason(),
            $helper->getErrorDescription()
        );
    }

    if (! $token->isLongLived()) {
        // OAuth 2.0 client handler
        $oauth_client = $fb->getOAuth2Client();

        // Extend the access token.
        try {
            $token = $oauth_client->getLongLivedAccessToken($token);
        } catch (Facebook\Exceptions\FacebookSDKException $e) {
            dd($e->getMessage());
        }
    }

    $fb->setDefaultAccessToken($token);

    // Save for later
    Session::put('fb_user_access_token', (string) $token);

    // Get basic info on the user from Facebook.
    try {
        $response = $fb->get('/me?fields=id,name,email');
    } catch (Facebook\Exceptions\FacebookSDKException $e) {
        dd($e->getMessage());
    }

    // Convert the response to a `Facebook/GraphNodes/GraphUser` collection
    $facebook_user = $response->getGraphUser();

    // Create the user if it does not exist or update the existing entry.
    // This will only work if you've added the SyncableGraphNodeTrait to your User model.
    $user = App\User::createOrUpdateGraphNode($facebook_user);

    // Log the user into Laravel
    Auth::login($user);

    return redirect('/')->with('message', 'Successfully logged in with Facebook');
});

Any help would really appreciated!
Thanks again,
xadim.

**Comment by SammyK** [comment]
Hey @xadim! Looks like you're using the Laravel Facebook SDK package. Can you [post this issue on that repo](https://github.com/SammyK/LaravelFacebookSdk/issues)? Also include what development environment you're using.

**Comment by xadim** [comment]
Yeah sure!
Thx
